typedef void * HANDLE;
typedef void * HDC;
typedef void * HWND;
typedef void * HINSTANCE;
typedef void * HMENU;
typedef void * HMODULE;
typedef void * HICON;
typedef void * HCURSOR;
typedef void * HBRUSH;
typedef int32_t BOOL;
typedef uint8_t BYTE;
typedef uint32_t UINT;
typedef uint32_t ULONG;
typedef int32_t LONG;
typedef uint16_t WCHAR;
typedef uint16_t WORD;
typedef WORD ATOM;
typedef uint32_t DWORD;
typedef uint64_t WPARAM;
typedef int64_t LPARAM;
typedef int64_t LRESULT;
typedef const WCHAR * LPCWSTR;
typedef LPCWSTR WSTR;
typedef struct { LONG cx; LONG cy; } SIZE;
typedef struct { LONG left; LONG top; LONG right; LONG bottom; } RECT;
typedef int64_t LONG_PTR;
typedef uint64_t ULONG_PTR;
typedef uint64_t UINT_PTR;
