typedef void * HWND;
typedef void * HINSTANCE;
typedef void * HMENU;
typedef void * HICON;
typedef void * HCURSOR;
typedef void * HBRUSH;
typedef int32_t BOOL;
typedef uint32_t UINT;
typedef int32_t LONG;
typedef uint16_t WCHAR;
typedef uint16_t WORD;
typedef WORD ATOM;
typedef uint32_t DWORD;
typedef uint64_t WPARAM;
typedef int64_t LPARAM;
typedef int64_t LRESULT;
typedef const WCHAR * LPCWSTR;
typedef LPCWSTR WSTR;
typedef struct { LONG left; LONG top; LONG right; LONG bottom; } RECT;
typedef uint64_t LONG_PTR;
